/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    stm32f4xx_it.c
  * @brief   Interrupt Service Routines
  ******************************************************************************
  */
/* USER CODE END Header */

#include "main.h"
#include "stm32f4xx_it.h"

/* extern peripheral handles from main.c */
extern TIM_HandleTypeDef htim3;
extern TIM_HandleTypeDef htim4;
extern UART_HandleTypeDef huart1;
extern UART_HandleTypeDef huart2;
extern UART_HandleTypeDef huart6;

/******************************************************************************/
/* Cortex-M4 Processor Interruption and Exception Handlers                    */
/******************************************************************************/

void SysTick_Handler(void)
{
  HAL_IncTick();
}

/******************************************************************************/
/* Peripheral Interrupt Handlers                                              */
/******************************************************************************/

void TIM3_IRQHandler(void)
{
  HAL_TIM_IRQHandler(&htim3);
}

/* If you need TIM4 IRQ for other features, keep it. For PWM we don't need TIM4 IRQ here. */
void TIM4_IRQHandler(void)
{
  HAL_TIM_IRQHandler(&htim4);
}

void USART1_IRQHandler(void)
{
  HAL_UART_IRQHandler(&huart1);
}

void USART2_IRQHandler(void)
{
  HAL_UART_IRQHandler(&huart2);
}

void USART6_IRQHandler(void)
{
  HAL_UART_IRQHandler(&huart6);
}

/* Add other IRQ handlers (EXTI, DMA, etc) as generated by CubeMX if required */
